version: "3.7"

services:
    redis:
        container_name: calendar_redis
        image: redis:5.0.6
        ports:
            - 6379:6379

    redis_commander:
        container_name: calendar_redis_commander
        image: rediscommander/redis-commander
        environment:
            - "REDIS_HOST=redis"
            - "REDIS_PORT=6379"
        ports:
            - "8081:8081"
        depends_on:
            - redis
